#!/bin/bash

CONF_PATH=/home/aki/Workplace/Git/CameraTrap/CameraTrap/config.ini

# Define a function to start the motion_script.py script
function start_motion {
    sed -i 's/running=.*/running='"true"'/g' $CONF_PATH
    python3 /home/aki/Workplace/Git/CameraTrap/CameraTrap/motcam_script.py &
}

# Define a function to edit the config.ini file
function edit_config {
    read -p "Enter the mode photo/video: " new_mode
    read -p "Enter the time value (in sec, time of recorded video, integer): " new_time
    read -p "Enter interval of captures(in sec, integer):" new_c_interval
    read -p "Enter interval of motion detection(in sec, integer):" new_md_interval
    sed -i 's/mode=.*/mode='"$new_mode"'/g' $CONF_PATH
    sed -i 's/time=.*/time='"$new_time"'/g' $CONF_PATH
    sed -i 's/capture_interval=.*/capture_interval='"$new_c_interval"'/g' $CONF_PATH
    sed -i 's/motion_detection_interval=.*/motion_detection_interval='"$new_md_interval"'/g' $CONF_PATH
}

#Define a function for stopping the motcam_script.py
function stop_motion {
    sed -i 's/running=.*/running='"false"'/g' $CONF_PATH
}

# Main script

if [ "$1" == "-edit" ]; then
    edit_config
elif [ "$1" == "-start" ]; then
    start_motion
elif [ "$1" == "-stop" ]; then
    stop_motion
else
    echo "Invalid argument. Usage: motcam [-edit | -start]"
fi
