#!/bin/bash

CONF_PATH=/home/aki/Workplace/Git/CameraTrap/config.ini

# Define a function to start the motion_script.py script
function start_motion {
    python motion_script.py &
}

# Define a function to edit the config.ini file
function edit_config {
    read -p "Enter the mode photo/video: " new_mode
    read -p "Enter the time value (in sec, time of recorded video): " new_time
    sed -i 's/mode=.*/mode='"$new_mode"'/g' $CONF_PATH
    sed -i 's/time=.*/time='"$new_time"'/g' $CONF_PATH
}

# Main script

if [ "$1" == "-edit" ]; then
    edit_config
elif [ "$1" == "-start" ]; then
    start_motion
else
    echo "Invalid argument. Usage: motcam [-edit | -start]"
fi
