#!/bin/bash

# Search for config.ini file using the find command
CONF_PATH=$(find / -name "config.ini" 2>/dev/null | grep "/MotCam/config.ini")

# Check if config_file variable is empty
if [ -z "$CONF_PATH" ]; then
  echo "Could not find config.ini file"
else
  echo "Found config.ini file at: $CONF_PATH"

# Define a function to start the motion_script.py script
function start_motion {
    sed -i 's/is_running=.*/is_running='"True"'/g' $CONF_PATH
    python3 /home/aki/Workplace/Git/CameraTrap/CameraTrap/MotCam/motcam_script.py &
}

# Define a function to edit the config.ini file
function edit_config {
    read -p "Enter the mode photo/video: " new_mode
    read -p "Enter the time value (in sec, time of recorded video, integer): " new_time
    sed -i 's/mode=.*/mode='"$new_mode"'/g' $CONF_PATH
    sed -i 's/time=.*/time='"$new_time"'/g' $CONF_PATH
}

#Define a function for stopping the motcam_script.py
function stop_motion {
    sed -i 's/is_running=.*/is_running='"False"'/g' $CONF_PATH
}

# Main script

if [ "$1" == "-edit" ]; then
    edit_config
elif [ "$1" == "-start" ]; then
    start_motion
elif [ "$1" == "-stop" ]; then
    stop_motion
else
    echo "Invalid argument. Usage: motcam [-edit | -start | -stop]"
fi
